### ISSUE TITLE
String with spaces

### ISSUE THREAD

**Issue by disconnect3d** [jay-g-mehta/pydhcpdparser#4]
Hey,

It seems to me that the three examples below should return exactly the same result. However, they don't because the current `STRING` token does not exclude whitespace characters: 

https://github.com/jay-g-mehta/pydhcpdparser/blob/96dd24eaefaa62b980a3e57bf5f685660a860372/pydhcpdparser/dhcp_conf_parser.py#L131

```python
In [2]: pydhcpdparser.parser.parse('zone 17.127.10.in-addr.arpa. { key DHCKUPDATE; }')
Out[2]: [{'zone': {'name': '17.127.10.in-addr.arpa. ', 'key': 'DHCKUPDATE'}}]

In [3]: pydhcpdparser.parser.parse('zone 17.127.10.in-addr.arpa.{ key DHCKUPDATE; }')
Out[3]: [{'zone': {'name': '17.127.10.in-addr.arpa.', 'key': 'DHCKUPDATE'}}]

In [4]: pydhcpdparser.parser.parse('zone 17.127.10.in-addr.arpa.   { key DHCKUPDATE; }')
Out[4]: [{'zone': {'name': '17.127.10.in-addr.arpa.   ', 'key': 'DHCKUPDATE'}}]
```

I am not that familiar with the format but is this correct as of the spec (if there is such)?

**Comment by jay-g-mehta** [comment]
This is explicitly left out, as design choice. pydhcpdparser should not interpret actual contents or white spaces and format or strip such things. Users of pydhcpdparser can perform string formatting, stripping of extra white spaces in this case, from the output.

**Comment by disconnect3d** [comment]
Okay, thx for info. It would probably be good to have an option for that but it is not a big deal to strip it on users end.
