### ISSUE TITLE
Handle "option" at global level

### ISSUE THREAD

**Issue by rharolde** [jay-g-mehta/pydhcpdparser#6]
It does not seem to handle "option" statements at the global level, which are common in my usage.

>>> from pydhcpdparser import parser
>>> conf = "option subnet-mask 255.255.255.0;"
>>> print(parser.parse(conf))
Syntax error in input! LexToken(OPTION,'option',1,0)
[{}]

See "Figure 2" on the dhcpd.conf man page, like
https://linux.die.net/man/5/dhcpd.conf

**Comment by jay-g-mehta** [comment]
Pushed out the fix on latest commit, not released on pypi yet.

**Comment by rharolde** [comment]
Thanks, but now it complains on the next word:
Syntax error in input! LexToken(SUBNET,'subnet',1,7)
