### ISSUE TITLE
range as subnet option do not work

### ISSUE THREAD

**Issue by dlyr** [jay-g-mehta/pydhcpdparser#7]
Hi,
I have trouble with pydhcpdparser (current pip version, but do not seems to have been corrected in last version): 
the range keyword is only recognized as a pool member, not direct subnet member.
The dhcpd.conf allow range as a direct subnet option.
Here are a minimal example:
```
subnet 192.168.16.0 netmask 255.255.255.0 {      
    option routers 192.168.16.1;
    option domain-name-servers 192.168.1.254;
    pool{
        range 192.168.16.100 192.168.16.200;
    }
}

subnet 192.168.32.0 netmask 255.255.255.0 {      
    option routers 192.168.32.1;
    option domain-name-servers 192.168.1.254;
    range 192.168.32.100 192.168.32.200;
}
```

got `Syntax error in input! LexToken(RANGE,'range',12,326)`

I'm not sure how to correct this, but feel free to ask if I can help.
++ dlyr

**Comment by jay-g-mehta** [comment]
pushed out new commit fixing this issue. Please check. If it looks good, I will release 0.0.10 on pypi

**Comment by dlyr** [comment]
works for me ! thanks.
